# Soring, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [3]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [3]:
x = np.array([[1,4],[3,1]])
np.sort(x,axis=1)

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [4]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
np.lexsort((surnames,first_names))

array([1, 2, 0], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [5]:
x = np.array([[1,4],[3,1]])
np.argsort(x,axis=1)

array([[0, 1],
       [1, 0]], dtype=int64)

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [21]:
x = np.random.permutation(10)
x2=x[np.argpartition(x,5)]
print ('x =');x2


x =


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [26]:
x = np.random.permutation(10)
x1=x[np.argpartition(x,3)]
print('x =');x1

x =


array([0, 1, 2, 3, 4, 5, 6, 8, 9, 7])

## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [29]:
x = np.random.permutation(10).reshape(2, 5);x

np.argmax(x,axis=1)

array([1, 2], dtype=int64)

Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [6]:
x = np.array([[np.nan, 4], [3, 2]])
np.argmax(x,axis=1)
np.argmin(x,axis=1)
np.nanargmax(x,axis=1)
np.nanargmin(x,axis=1)

array([1, 0], dtype=int64)

Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [113]:
x = np.array([[1, 2, 3], [1, 3, 5]])
np.

Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [100]:
x = np.array([[1, 2, 3], [1, 3, 5]])


[0 1 2 3 4 5]


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [105]:
x = np.arange(-5, 4).reshape(3, 3)


[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [10]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x,y)

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [8]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5