# Array manipulation routines

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.5'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [2]:
np.ones((10,10,3)).reshape(2,150)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.,

Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [10]:
x = np.array([[1,2,3],[4,5,6]]);x


array([[1, 2, 3, 4, 5, 6]])

Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [5]:
x = np.array([1,2,3,4,5,6])
x[4]

5

Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


In [15]:
x=np.arange(60).reshape((3,4,5));x
x.resize((4,3,5))
x.shape

(4, 3, 5)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [16]:
x=np.arange(12).reshape((3,4));x
x.resize((4,3))
x.shape

(4, 3)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [5]:
x=np.arange(12).reshape((3,4));x
y=np.expand_dims(x,axis=1)
y.shape

(3, 1, 4)

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [6]:
x=np.arange(12).reshape((3,4,1));x
y=np.squeeze(x,axis=2)
y.shape

(3, 4)

Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


In [25]:
x=np.arange(1,7).reshape((2,3));x
y=np.arange(7,13).reshape((2,3));y
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [26]:
x=np.arange(1,7).reshape((2,3));x
y=np.arange(7,13).reshape((2,3));y
np.concatenate((x,y),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [7]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.stack((x,y),axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])


Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [11]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.column_stack((x,y))

array([[1, 4],
       [2, 5],
       [3, 6]])

Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [71]:
x=np.arange(1,10);x
np.hsplit(x,(4,6))

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

In [4]:
x=np.arange(16).reshape((2,2,4));x
np.dsplit(x,(3,4))

[array([[[ 0,  1,  2],
         [ 4,  5,  6]],
 
        [[ 8,  9, 10],
         [12, 13, 14]]]),
 array([[[ 3],
         [ 7]],
 
        [[11],
         [15]]]),
 array([], shape=(2, 2, 0), dtype=int32)]

Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [95]:
x=np.arange(16).reshape((4,4));x
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [96]:
x=np.arange(16).reshape((4,4))
np.vsplit(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [2]:
x=np.array([0,1,2])
np.tile(x, (2, 2))


array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [106]:
x=np.array([0,1,2])
np.repeat(x,2)

array([0, 0, 1, 1, 2, 2])

Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [107]:
x=np.array([0,0,0,1,2,3,0,2,1,0])
np.trim_zeros(x)

array([1, 2, 3, 0, 2, 1])

Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [8]:
x=np.array([2,2,1,5,4,5,1,2,3])
np.unique(x,return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 3, 1, 1, 2], dtype=int64))

Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [109]:
x=np.array([[1,2],[3,4]]);x
np.flip(x,axis=1)

array([[2, 1],
       [4, 3]])

Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [110]:
x=np.array([[1,2],[3,4]]);x
np.flip(x,axis=0)

array([[3, 4],
       [1, 2]])

Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [119]:
x=np.array([[1,2],[3,4]]);x
np.rot90(x)

array([[2, 4],
       [1, 3]])

Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [4]:
x=np.array([[1,2,3,4],[5,6,7,8]]);x
np.roll(x,1,axis=1)

array([[4, 1, 2, 3],
       [8, 5, 6, 7]])