# Logic functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

## Truth value testing


Q1. Let x be an arbitrary array. Return True if none of the elements of x is zero. Remind that 0 evaluates to False in python.


In [7]:
x = np.array([1,2,3])
np.all(x)

x = np.array([1,0,3])
np.all(x)

True

Q2. Let x be an arbitrary array. Return True if any of the elements of x is non-zero.

In [9]:
x = np.array([1,0,0])
np.any(x)
x = np.array([0,0,0])
np.any(x)

False

## Array contents


Q3. Predict the result of the following code.

In [10]:
x = np.array([1, 0, np.nan, np.inf])
np.isfinite(x)

array([ True,  True, False, False])

Q4. Predict the result of the following code.

In [11]:
x = np.array([1, 0, np.nan, np.inf])
np.isinf(x)

array([False, False, False,  True])

Q5. Predict the result of the following code.

In [12]:
x = np.array([1, 0, np.nan, np.inf])
np.isnan(x)

array([False, False,  True, False])

## Array type testing

Q6. Predict the result of the following code.

In [13]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
np.iscomplex(x)

array([ True, False, False, False, False,  True])

Q7. Predict the result of the following code.

In [14]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
np.isreal(x)

array([False,  True,  True,  True,  True, False])

Q8. Predict the result of the following code.

In [17]:
np.isscalar(3)
np.isscalar([3])
np.isscalar(True)

True

## Logical operations

Q9. Predict the result of the following code.

In [19]:
np.logical_and([True, False], [False, False])
np.logical_or([True, False, True], [True, False, False])
np.logical_xor([True, False, True], [True, False, False])
np.logical_not([True, False, 0, 1])


array([ True, False,  True])

## Comparison

Q10. Predict the result of the following code.

In [21]:
np.allclose([3], [2.999999])
np.array_equal([3], [2.999999])

False

Q11. Write numpy comparison functions such that they return the results as you see.

In [25]:
x = np.array([4, 5])
y = np.array([2, 5])
np.not_equal(x,y)
np.greater_equal(x,y)
np.less(x,y)
np.less_equal(x,y)

array([False,  True])

Q12. Predict the result of the following code.

In [27]:
np.equal([1, 2], [1, 2.000001])
np.isclose([1, 2], [1, 2.000001])

array([ True,  True])