# Mathematical functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

## Trigonometric functions

Q1. Calculate sine, cosine, and tangent of x, element-wise.

In [5]:
x = np.array([0., 1., 30, 90])
np.sin(x)
np.cos(x)
np.tan(x)

array([ 0.        ,  1.55740772, -6.4053312 , -1.99520041])

Q2. Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.

In [12]:
x = np.array([-1., 0, 1.])
np.arcsin(x)
np.arccos(x)
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

Q3. Convert angles from radians to degrees.

In [13]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
np.degrees(x)

array([-180.,  -90.,   90.,  180.])

Q4. Convert angles from degrees to radians.

In [14]:
x = np.array([-180.,  -90.,   90.,  180.])
np.radians(x)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

## Hyperbolic functions

Q5. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.

In [17]:
x = np.array([-1., 0, 1.])
np.sinh(x)
np.cosh(x)
np.tanh(x)

array([-0.76159416,  0.        ,  0.76159416])

## Rounding

Q6. Predict the results of these, paying attention to the difference among the family functions.

In [22]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])

out1 = np.around(x) 
out2 = np.floor(x)
out3 = np.ceil(x)
out4 = np.trunc(x)
out5 = [round(elem) for elem in x]

print(out1)
print(out2)
print(out3)
print(out4)
print(out5)


[ 2.  2.  2.  3. -2. -2. -3.]
[ 2.  1.  2.  2. -3. -3. -3.]
[ 3.  2.  3.  3. -2. -2. -2.]
[ 2.  1.  2.  2. -2. -2. -2.]
[2.0, 2.0, 2.0, 3.0, -2.0, -2.0, -3.0]


Q7. Implement out5 in the above question using numpy.

[ 2.  2.  3.  3. -2. -3. -3.]


## Sums, products, differences

Q8. Predict the results of these.

In [23]:
x = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]])

outs = [np.sum(x),
        np.sum(x, axis=0),
        np.sum(x, axis=1, keepdims=True),
        "",
        np.prod(x),
        np.prod(x, axis=0),
        np.prod(x, axis=1, keepdims=True),
        "",
        np.cumsum(x),
        np.cumsum(x, axis=0),
        np.cumsum(x, axis=1),
        "",
        np.cumprod(x),
        np.cumprod(x, axis=0),
        np.cumprod(x, axis=1),
        "",
        np.min(x),
        np.min(x, axis=0),
        np.min(x, axis=1, keepdims=True),
        "",
        np.max(x),
        np.max(x, axis=0),
        np.max(x, axis=1, keepdims=True),
        "",
        np.mean(x),
        np.mean(x, axis=0),
        np.mean(x, axis=1, keepdims=True)]
           
for out in outs:
    if out == "":
        pass
        print
    else:
        pass
        print("->", out)


-> 36
-> [ 6  8 10 12]
-> [[10]
 [26]]
-> 40320
-> [ 5 12 21 32]
-> [[  24]
 [1680]]
-> [ 1  3  6 10 15 21 28 36]
-> [[ 1  2  3  4]
 [ 6  8 10 12]]
-> [[ 1  3  6 10]
 [ 5 11 18 26]]
-> [    1     2     6    24   120   720  5040 40320]
-> [[ 1  2  3  4]
 [ 5 12 21 32]]
-> [[   1    2    6   24]
 [   5   30  210 1680]]
-> 1
-> [1 2 3 4]
-> [[1]
 [5]]
-> 8
-> [5 6 7 8]
-> [[4]
 [8]]
-> 4.5
-> [3. 4. 5. 6.]
-> [[2.5]
 [6.5]]


Q9. Calculate the difference between neighboring elements, element-wise.

In [24]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)

array([ 1,  2,  3, -7])

Q10. Calculate the difference between neighboring elements, element-wise, and
prepend [0, 0] and append[100] to it.

In [35]:
x = np.array([1, 2, 4, 7, 0])
x1=np.ediff1d(x)
x2=np.append(x1,100)
a=np.array([0,0])
np.append(a,x2)

array([  0,   0,   1,   2,   3,  -7, 100])

Q11. Return the cross product of x and y.

In [26]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.cross(x,y)


array([-3,  6, -3])

## Exponents and logarithms

Q12. Compute $e^x$, element-wise.

In [27]:
x = np.array([1., 2., 3.], np.float32)

np.exp(x)

array([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)

Q13. Calculate exp(x) - 1 for all elements in x.

In [28]:
x = np.array([1., 2., 3.], np.float32)
np.expm1(x)

array([ 1.7182817,  6.389056 , 19.085537 ], dtype=float32)

Q14. Calculate $2^p$ for all p in x.

In [29]:
x = np.array([1., 2., 3.], np.float32)
np.exp2(x)

array([2., 4., 8.], dtype=float32)

Q15. Compute natural, base 10, and base 2 logarithms of x element-wise.

In [33]:
x = np.array([1, np.e, np.e**2])
np.log(x)
np.log10(x)
np.log2(x)

array([0.        , 1.44269504, 2.88539008])

Q16. Compute the natural logarithm of one plus each element in x in floating-point accuracy.

In [37]:
x = np.array([1e-99, 1e-100])
np.log1p(x)

array([1.e-099, 1.e-100])

## Floating point routines

Q17. Return element-wise True where signbit is set.

In [38]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])

np.signbit(x)

array([ True,  True,  True, False, False, False, False])

Q18. Change the sign of x to that of y, element-wise.

In [39]:
x = np.array([-1, 0, 1])
y = -1.1
np.copysign(x,y)

array([-1., -0., -1.])

## Arithmetic operations

Q19. Add x and y element-wise.

In [40]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])

np.add(x,y)

array([0, 0, 0])

Q20. Subtract y from x element-wise.

In [41]:
x = np.array([3, 4, 5])
y = np.array(3)

np.subtract(x,y)

array([0, 1, 2])

Q21. Multiply x by y element-wise.

In [42]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])

np.multiply(x,y)

array([ 3,  0, -5])

Q22. Divide x by y element-wise in two different ways.

In [45]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
np.divide(x,y)
np.floor_divide(x,y)

array([3., 2., 1.])

Q23. Compute numerical negative value of x, element-wise.

In [46]:
x = np.array([1, -1])
np.negative(x)

array([-1,  1])

Q24. Compute the reciprocal of x, element-wise.

In [47]:
x = np.array([1., 2., .2])
np.reciprocal(x)

array([1. , 0.5, 5. ])

Q25. Compute $x^y$, element-wise.

In [48]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
np.power(x,y)

array([[ 1,  4],
       [ 3, 16]], dtype=int32)

Q26. Compute the remainder of x / y element-wise in two different ways.

In [51]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
np.fmod(x,y)
np.mod(x,y)


array([1, 0, 1, 1, 0, 1], dtype=int32)

## Miscellaneous

Q27. If an element of x is smaller than 3, replace it with 3.
And if an element of x is bigger than 7, replace it with 7.

In [52]:
x = np.arange(10)
np.clip(x,3,7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

Q28. Compute the square of x, element-wise.

In [53]:
x = np.array([1, 2, -1])
np.square(x)

array([1, 4, 1], dtype=int32)

Q29. Compute square root of x element-wise.


In [54]:
x = np.array([1., 4., 9.])
np.sqrt(x)

array([1., 2., 3.])

Q30. Compute the absolute value of x.

In [55]:
x = np.array([[1, -1], [3, -3]])
np.absolute(x)


array([[1, 1],
       [3, 3]])

Q31. Compute an element-wise indication of the sign of x, element-wise.

In [56]:
x = np.array([1, 3, 0, -1, -3])
np.sign(x)

array([ 1,  1,  0, -1, -1])