# Random Sampling

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.5'

In [5]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [3]:
np.random.uniform(0,1,(3,2))

array([[0.06017394, 0.0347118 ],
       [0.84089968, 0.6561958 ],
       [0.69840533, 0.40702375]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [5]:
x=np.random.randn(1000,1000)
x.mean()

-0.0008459603093211523

In [6]:
x.std()

0.998791260837068

Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [7]:
np.array(np.random.uniform(0,3,(3,2)),dtype=int)

array([[2, 0],
       [2, 1],
       [1, 2]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [11]:
np.random.seed(0)
p = np.array([0.3,0.5,0.2])
result=np.random.choice(['3 out of 10', '5 out of 10', '2 out of 10'], p = p.ravel())
for i in range(10):
    print("",result) # ？？？

5 out of 10
 5 out of 10
 5 out of 10
 5 out of 10
 5 out of 10
 5 out of 10
 5 out of 10
 5 out of 10
 5 out of 10
 5 out of 10


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [13]:
np.random.choice(10,3,replace=False,p = [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1])

array([6, 4, 8])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [14]:
x=np.arange(10)
np.random.shuffle(x)
x

array([5, 2, 3, 4, 9, 0, 7, 6, 1, 8])

In [17]:
# Or
x=np.arange(10)
np.random.permutation(x)

array([1, 8, 9, 5, 2, 6, 3, 7, 4, 0])

## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [19]:
np.random.seed(10)