# Soring, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.5'

In [3]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [3]:
x = np.array([[1,4],[3,1]])
x.sort(axis=1)
x

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [2]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
x=np.array(['Heinrich', 'Galileo', 'Gustav'])
np.lexsort((surnames,first_names))

array([1, 2, 0], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [5]:
x = np.array([[1,4],[3,1]])
np.argsort(x)

array([[0, 1],
       [1, 0]], dtype=int64)

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [48]:
x = np.random.permutation(10)
print("x =", x)


x = [5 1 6 3 9 8 2 7 4 0]

Check the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5
[2 0 4 3 1 5 8 7 6 9]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [56]:
x = np.random.permutation(10)
print("x =", x)


x = [2 8 3 7 5 6 4 0 9 1]
partitioned = [0 1 2 3 4 5 8 6 9 7]
indices = [0 1 2 3 4 5 8 6 9 7]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [6]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)

x = [[7 0 8 2 4]
 [9 1 3 5 6]]


In [11]:
max=np.amax(x,axis=1)
print("maximum values=",max)

maximum values= [8 9]


In [12]:
maxid=np.argmax(x,axis=1)
print("max indices=",maxid)

max indices= [2 0]


In [13]:
min=np.amin(x,axis=1)
print("minimum values=",min)

minimum values= [0 1]


In [14]:
minid=np.argmin(x,axis=1)
print("min indices=",minid)

min indices= [1 1]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [15]:
x = np.array([[np.nan, 4], [3, 2]])

In [16]:
max=np.nanmax(x,axis=1)
print("maximum values ignoring NaNs=",max)

maximum values ignoring NaNs= [4. 3.]


In [17]:
maxid=np.nanargmax(x,axis=1)
print("max indices=",maxid)

max indices= [1 0]


In [18]:
min=np.nanmin(x,axis=1)
print("minimum values ignoring NaNs=",min)

minimum values ignoring NaNs= [4. 2.]


In [19]:
minid=np.nanargmin(x,axis=1)
print("min indices=",minid)

min indices= [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [20]:
x = np.array([[1, 2, 3], [1, 3, 5]])
values=np.extract(x>2,x)
print("Values bigger than 2 =",values)

Values bigger than 2 = [3 3 5]


In [22]:
ids=np.argwhere(x>2).T
print("Their indices are",ids)

Their indices are [[0 1 1]
 [2 1 2]]


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [23]:
x = np.array([[1, 2, 3], [1, 3, 5]])
y=x.ravel()
np.extract(y>2,y)

array([3, 3, 5])

Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [24]:
x = np.arange(-5, 4).reshape(3, 3)
x[x<0]=0
x

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [25]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x,y)

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [27]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5