# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.5'

## Matrix and vector products

Q1. Predict the results of the following code.

In [5]:
x = [1,2]
y = [[4, 1], [2, 2]]
#print np.dot(x, y)
np.dot(x,y)

array([8, 5])

In [6]:
#print np.dot(y, x)
np.dot(y,x)

array([6, 6])

In [7]:
#print np.matmul(x, y)
np.matmul(x,y)

array([8, 5])

In [8]:
#print np.inner(x, y)
np.inner(x,y)

array([6, 6])

In [9]:
#print np.inner(y, x)
np.inner(y,x)

array([6, 6])

Q2. Predict the results of the following code.

In [10]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
#print np.dot(y, x)
np.dot(y,x)

array([[4, 1],
       [2, 2],
       [1, 1]])

In [11]:
#print np.matmul(y, x)
np.matmul(y,x)

array([[4, 1],
       [2, 2],
       [1, 1]])

Q3. Predict the results of the following code.

In [12]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
#print np.vdot(x, y)
np.vdot(x,y)

30

In [13]:
#print np.vdot(y, x)
np.vdot(y,x)

30

In [14]:
#print np.dot(x.flatten(), y.flatten())
np.dot(x.flatten(),y.flatten())

30

In [15]:
#print np.inner(x.flatten(), y.flatten())
np.inner(x.flatten(),y.flatten())

30

In [16]:
#print (x*y).sum()
(x*y).sum()

30

Q4. Predict the results of the following code.

In [17]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
#print np.inner(x, y)
np.inner(x,y)

'abb'

In [18]:
#print np.inner(y, x)
np.inner(y,x)

'abb'

In [19]:
#print np.outer(x, y)
np.outer(x,y)

array([['a', 'aa'],
       ['b', 'bb']], dtype=object)

In [20]:
#print np.outer(y, x)
np.outer(y,x)

array([['a', 'b'],
       ['aa', 'bb']], dtype=object)

## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [21]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
np.linalg.cholesky(x)

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

Q6. Compute the qr factorization of x and verify it.

In [22]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q,r=np.linalg.qr(x)
print("q=",q)
print("r=",r)

q= [[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]]
r= [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [23]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
U,s,V=np.linalg.svd(x)
print("U=",U)
print("s=",s)
print("V=",V)

U= [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
s= [3.       2.236068 2.       0.      ]
V= [[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]
 [-0.8944272  0.         0.         0.         0.4472136]]


## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [26]:
x = np.diag((1, 2, 3))
eigenvals,eigenvecs=np.linalg.eig(x)
print("eigenvalues are",eigenvals)
print("eigenvectors are",eigenvecs)

eigenvalues are [1. 2. 3.]
eigenvectors are [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q9. Predict the results of the following code.

In [27]:
#print np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs)
np.array_equal(np.dot(x,eigenvecs),eigenvals*eigenvecs)

True

## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [30]:
x = np.arange(1, 10).reshape((3, 3))
np.linalg.norm(x,'fro')

16.881943016134134

In [31]:
np.linalg.cond(x)

5.0522794445385096e+16

Q11. Calculate the determinant of x.

In [32]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.det(x)

-2.0000000000000004

Q12. Calculate the rank of x.

In [33]:
x = np.eye(4)
np.linalg.matrix_rank(x)

4

Q13. Compute the sign and natural logarithm of the determinant of x.

In [34]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.slogdet(x)

(-1.0, 0.6931471805599455)

Q14. Return the sum along the diagonal of x.

In [35]:
x = np.eye(4)
np.trace(x)

4.0

## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [37]:
x = np.array([[1., 2.], [3., 4.]])
np.linalg.tensorinv(x,ind=1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])