# Mathematical functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.5'

## Trigonometric functions

Q1. Calculate sine, cosine, and tangent of x, element-wise.

In [3]:
x = np.array([0., 1., 30, 90])
sin=np.sin(x)
cos=np.cos(x)
tan=np.tan(x)
print("sine:",sin)
print("cosine",cos)
print("tangent",tan)

sine: [ 0.          0.84147098 -0.98803162  0.89399666]
cosine [ 1.          0.54030231  0.15425145 -0.44807362]
tangent [ 0.          1.55740772 -6.4053312  -1.99520041]


Q2. Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.

In [4]:
x = np.array([-1., 0, 1.])
arcsin=np.arcsin(x)
arccos=np.arccos(x)
arctan=np.arctan(x)
print("inverse sine:",arcsin)
print("inverse cosine",arccos)
print("inverse tangent",arctan)

inverse sine: [-1.57079633  0.          1.57079633]
inverse cosine [3.14159265 1.57079633 0.        ]
inverse tangent [-0.78539816  0.          0.78539816]


Q3. Convert angles from radians to degrees.

In [5]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
np.rad2deg(x)

array([-180.,  -90.,   90.,  180.])

Q4. Convert angles from degrees to radians.

In [6]:
x = np.array([-180.,  -90.,   90.,  180.])
np.deg2rad(x)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

## Hyperbolic functions

Q5. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.

In [8]:
x = np.array([-1., 0, 1.])
np.sinh(x)

array([-1.17520119,  0.        ,  1.17520119])

In [9]:
np.cosh(x)

array([1.54308063, 1.        , 1.54308063])

In [10]:
np.tanh(x)

array([-0.76159416,  0.        ,  0.76159416])

## Rounding

Q6. Predict the results of these, paying attention to the difference among the family functions.

In [12]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])

out1 = np.around(x) # 平均舍入
out2 = np.floor(x) # 往下取整
out3 = np.ceil(x) # 往上取整
out4 = np.trunc(x) # 去掉小数位
out5 = [round(elem) for elem in x] # ？？？

In [13]:
out1

array([ 2.,  2.,  2.,  3., -2., -2., -3.])

In [14]:
out2

array([ 2.,  1.,  2.,  2., -3., -3., -3.])

In [15]:
out3

array([ 3.,  2.,  3.,  3., -2., -2., -2.])

In [16]:
out4

array([ 2.,  1.,  2.,  2., -2., -2., -2.])

In [17]:
out5

[2.0, 2.0, 2.0, 3.0, -2.0, -2.0, -3.0]

Q7. Implement out5 in the above question using numpy.

In [18]:
np.rint(x) # 四舍五入有问题

array([ 2.,  2.,  2.,  3., -2., -2., -3.])

## Sums, products, differences

Q8. Predict the results of these.

In [19]:
x = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]])

outs = [np.sum(x),
        np.sum(x, axis=0),
        np.sum(x, axis=1, keepdims=True),
        "out", # 总和
        np.prod(x),
        np.prod(x, axis=0),
        np.prod(x, axis=1, keepdims=True),
        "out", # 乘积
        np.cumsum(x),
        np.cumsum(x, axis=0),
        np.cumsum(x, axis=1),
        "out", # 元素的累加和
        np.cumprod(x),
        np.cumprod(x, axis=0),
        np.cumprod(x, axis=1),
        "out", # 元素的累积积
        np.min(x),
        np.min(x, axis=0),
        np.min(x, axis=1, keepdims=True),
        "out",
        np.max(x),
        np.max(x, axis=0),
        np.max(x, axis=1, keepdims=True),
        "out",
        np.mean(x),
        np.mean(x, axis=0),
        np.mean(x, axis=1, keepdims=True)]
           
for out in outs:
    if out == "":
        pass
        #print
    else:
        pass
        #print("->", out)

Q9. Calculate the difference between neighboring elements, element-wise.

In [20]:
x = np.array([1, 2, 4, 7, 0])
np.ediff1d(x)

array([ 1,  2,  3, -7])

Q10. Calculate the difference between neighboring elements, element-wise, and
prepend [0, 0] and append[100] to it.

In [22]:
x = np.array([1, 2, 4, 7, 0])
y=np.ediff1d(x)
z=np.append(y,100)
a=np.array([0,0])
np.append(a,z)

array([  0,   0,   1,   2,   3,  -7, 100])

Q11. Return the cross product of x and y.

In [21]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.cross(x,y)

array([-3,  6, -3])

## Exponents and logarithms

Q12. Compute $e^x$, element-wise.

In [2]:
x = np.array([1., 2., 3.], np.float32)
np.exp(x)

array([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)

Q13. Calculate exp(x) - 1 for all elements in x.

In [3]:
x = np.array([1., 2., 3.], np.float32)
np.exp(x)-1

array([ 1.7182817,  6.389056 , 19.085537 ], dtype=float32)

Q14. Calculate $2^p$ for all p in x.

In [4]:
x = np.array([1., 2., 3.], np.float32)
np.exp2(x)

array([2., 4., 8.], dtype=float32)

Q15. Compute natural, base 10, and base 2 logarithms of x element-wise.

In [5]:
x = np.array([1, np.e, np.e**2])
natural=np.log(x)
base10=np.log10(x)
base2=np.log2(x)
print("natural log =",natural)
print("common log =",base10)
print("base 2 log =",base2)

natural log = [0. 1. 2.]
common log = [0.         0.43429448 0.86858896]
base 2 log = [0.         1.44269504 2.88539008]


Q16. Compute the natural logarithm of one plus each element in x in floating-point accuracy.

In [6]:
x = np.array([1e-99, 1e-100])
np.log(x+1) # 精确度

array([0., 0.])

## Floating point routines

Q17. Return element-wise True where signbit is set.

In [7]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])
np.signbit(x)

array([ True,  True,  True, False, False, False, False])

Q18. Change the sign of x to that of y, element-wise.

In [8]:
x = np.array([-1, 0, 1])
y = -1.1
np.copysign(x,y)

array([-1., -0., -1.])

## Arithmetic operations

Q19. Add x and y element-wise.

In [9]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])
np.add(x,y)

array([0, 0, 0])

Q20. Subtract y from x element-wise.

In [10]:
x = np.array([3, 4, 5])
y = np.array(3)
np.subtract(x,y)

array([0, 1, 2])

Q21. Multiply x by y element-wise.

In [11]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])
np.multiply(x,y)

array([ 3,  0, -5])

Q22. Divide x by y element-wise in two different ways.

In [12]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
np.divide(x,y)

array([3.        , 2.        , 1.66666667])

In [13]:
np.floor_divide(x,y)

array([3., 2., 1.])

Q23. Compute numerical negative value of x, element-wise.

In [14]:
x = np.array([1, -1])
np.negative(x)

array([-1,  1])

Q24. Compute the reciprocal of x, element-wise.

In [15]:
x = np.array([1., 2., .2])
np.reciprocal(x)

array([1. , 0.5, 5. ])

Q25. Compute $x^y$, element-wise.

In [16]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
np.power(x,y)

array([[ 1,  4],
       [ 3, 16]], dtype=int32)

Q26. Compute the remainder of x / y element-wise in two different ways.

In [17]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
np.remainder(x,y)

array([1, 0, 1, 1, 0, 1], dtype=int32)

In [18]:
np.fmod(x,y)

array([-1,  0, -1,  1,  0,  1], dtype=int32)

## Miscellaneous

Q27. If an element of x is smaller than 3, replace it with 3.
And if an element of x is bigger than 7, replace it with 7.

In [19]:
x = np.arange(10)
np.clip(x,3,7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

Q28. Compute the square of x, element-wise.

In [20]:
x = np.array([1, 2, -1])
np.square(x)

array([1, 4, 1], dtype=int32)

Q29. Compute square root of x element-wise.


In [21]:
x = np.array([1., 4., 9.])
np.sqrt(x)

array([1., 2., 3.])

Q30. Compute the absolute value of x.

In [22]:
x = np.array([[1, -1], [3, -3]])
np.absolute(x)

array([[1, 1],
       [3, 3]])

Q31. Compute an element-wise indication of the sign of x, element-wise.

In [23]:
x = np.array([1, 3, 0, -1, -3])
np.sign(x)

array([ 1,  1,  0, -1, -1])