# Random Sampling

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [5]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [3]:
np.random.rand(3,2)

array([[0.96417505, 0.56466893],
       [0.56629956, 0.68865539],
       [0.03408219, 0.14769998]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [10]:
x = np.random.randn(1000,1000)
np.mean(x)
np.std(x)

1.0004036142324662

Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [44]:
np.random.random_integers(0,3,size=(3,2))

array([[1, 3],
       [3, 0],
       [0, 0]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [3]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']
np.random.choice(x,10,p=[0.3,0.5,0.2])

5 out of 10
2 out of 10
3 out of 10
5 out of 10
2 out of 10
5 out of 10
2 out of 10
2 out of 10
2 out of 10
5 out of 10


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [66]:
np.random.choice(10,3,replace = False)

array([5, 4, 0])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [14]:
x = np.arange(10)
np.random.shuffle(x)
x

array([8, 2, 5, 4, 6, 9, 1, 7, 0, 3])

In [21]:
y = np.random.permutation(x)
y


array([2, 3, 4, 6, 8, 0, 1, 7, 9, 5])

## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [23]:
np.random.seed(10)